# Generated by Django 3.2.8 on 2021-10-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211005_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
