# Generated by Django 3.2.8 on 2021-10-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
